import Link from"next/link";import{Header}from"@/components/header";import{Footer}from"@/components/footer";import{ContactForm}from"@/components/contact-form";import{programs,news}from"@/lib/data";
const facilities=[['Laboratorium Terpadu','Ruang eksperimen sains dan komputer dengan perangkat pembelajaran mutakhir.'],['Perpustakaan Kolaboratif','Koleksi terkurasi, area diskusi, dan akses referensi digital.'],['Arena Olahraga','Lapangan multifungsi dan studio kebugaran untuk pengembangan fisik siswa.']];
export default function Home(){return <><Header/><main><section className="hero"><div className="container content"><span className="eyebrow" style={{color:'#77d5ca'}}>Pendidikan untuk masa depan</span><h1>Tumbuh Berkarakter.<br/>Melangkah Mendunia.</h1><p>SMA Cakrawala Nusantara menghadirkan pendidikan akademik yang kuat, pembentukan karakter, dan pengalaman belajar relevan untuk menyiapkan generasi masa depan.</p><div className="hero-actions"><Link href="/ppdb" className="btn primary">Daftar PPDB</Link><a href="#profil" className="btn outline">Jelajahi sekolah</a></div></div></section>
<section id="profil" className="section"><div className="container split"><div><span className="eyebrow">Tentang kami</span><h2 className="title">Sekolah tempat potensi menemukan arah.</h2><p className="muted">Sejak 1998, Cakrawala Nusantara mendampingi siswa menjadi pembelajar mandiri yang berintegritas. Kurikulum nasional diperkaya pendekatan berbasis proyek, literasi digital, dan pengalaman kontekstual.</p><div className="grid3" style={{marginTop:28}}><div><b>Visi</b><p className="muted">Menjadi sekolah unggul yang melahirkan pemimpin berkarakter dan berwawasan global.</p></div><div><b>Misi</b><p className="muted">Menyelenggarakan pembelajaran bermakna, inklusif, dan berorientasi masa depan.</p></div></div></div><div className="photo" role="img" aria-label="Siswa belajar bersama di ruang kelas" style={{backgroundImage:"url('https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=85')"}}/></div></section>
<section className="section alt" id="program"><div className="container"><span className="eyebrow">Program unggulan</span><h2 className="title">Belajar melampaui ruang kelas.</h2><div className="grid3">{programs.map((p,i)=><article className="card" key={p[0]}><span className="tag">0{i+1}</span><h3>{p[0]}</h3><p className="muted">{p[1]}</p></article>)}</div></div></section>
<section className="section"><div className="container"><span className="eyebrow">Fasilitas</span><h2 className="title">Ruang yang mendukung setiap proses.</h2><div className="grid3">{facilities.map((x,i)=><article key={x[0]} className="card"><div className="photo" style={{minHeight:190,backgroundImage:`url('https://images.unsplash.com/photo-${['1564981797816-1043664bf78d','1562774053-701939374585','1577896851231-70ef18881754'][i]}?auto=format&fit=crop&w=800&q=80')`}}/><h3>{x[0]}</h3><p className="muted">{x[1]}</p></article>)}</div></div></section>
<section className="section"><div className="container stats">{[['1.240','Siswa aktif'],['86','Guru & tenaga ahli'],['32','Program prestasi'],['98%','Lulusan ke perguruan tinggi']].map(x=><div className="stat" key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>
<section id="berita" className="section alt"><div className="container"><span className="eyebrow">Kabar sekolah</span><h2 className="title">Berita dan agenda terbaru.</h2><div className="grid3">{news.map(n=><article className="card" key={n.slug}><span className="tag">{n.date}</span><h3>{n.title}</h3><p className="muted">{n.text}</p><Link className="tag" href={`/berita/${n.slug}`}>Baca selengkapnya →</Link></article>)}</div></div></section>
<section className="section"><div className="container split"><div><span className="eyebrow">Suara komunitas</span><h2 className="title">Kepercayaan yang tumbuh dari pengalaman.</h2></div><blockquote className="card quote">“Guru tidak hanya menjelaskan materi, tetapi membantu anak kami menemukan keberanian untuk bertanya dan bertanggung jawab atas pilihannya.”<footer style={{marginTop:18}}><b>Rina Prameswari</b><br/><span className="muted">Orang tua siswa kelas XI</span></footer></blockquote></div></section>
<section className="section alt"><div className="container"><span className="eyebrow">Galeri kegiatan</span><h2 className="title">Momen belajar, berkarya, dan bertumbuh.</h2><div className="gallery">{['photo-1541339907198-e08756dedf3f','photo-1509062522246-3755977927d7','photo-1529390079861-591de354faf5'].map((x,i)=><div key={x} className="photo" role="img" aria-label={['Kegiatan siswa di kampus','Pembelajaran kolaboratif','Kegiatan komunitas siswa'][i]} style={{backgroundImage:`url('https://images.unsplash.com/${x}?auto=format&fit=crop&w=1000&q=80')`}}/>)}</div></div></section>
<section id="kontak" className="section"><div className="container split"><div><span className="eyebrow">Hubungi kami</span><h2 className="title">Mari kenal Cakrawala lebih dekat.</h2><p className="muted">Tanyakan proses penerimaan, jadwalkan kunjungan, atau diskusikan kebutuhan pendidikan putra-putri Anda.</p></div><div className="card"><ContactForm/></div></div></section></main><Footer/></>}
